import TradingDay from "../models/TradingDay";

export const market: TradingDay = {
  advancing: [
    {
      ticker: "138SL",
      name: "138 STUDENT LIVING JAMAICA LIMITED",
      volume: "396",
      c_price: "5.25",
      price_change: "0.04",
      change: "0.77",
    },
    {
      ticker: "AFS",
      name: "ACCESS FINANCIAL SERVICES LIMITED",
      volume: "24,058",
      c_price: "21.47",
      price_change: "0.61",
      change: "2.92",
    },
    {
      ticker: "AMG",
      name: "AMG PACKAGING  & PAPER COMPANY LIMITED",
      volume: "29,136",
      c_price: "3.83",
      price_change: "0.01",
      change: "0.26",
    },
    {
      ticker: "BPOW",
      name: "BLUE POWER GROUP LIMITED",
      volume: "1,857",
      c_price: "3.58",
      price_change: "0.02",
      change: "0.56",
    },
    {
      ticker: "CAC",
      name: "CAC 2000 LIMITED",
      volume: "1,668",
      c_price: "6.60",
      price_change: "0.60",
      change: "10.00",
    },
    {
      ticker: "CHL",
      name: "CARGO HANDLERS LIMITED",
      volume: "53,171",
      c_price: "12.26",
      price_change: "0.15",
      change: "1.24",
    },
    {
      ticker: "CABROKERS",
      name: "CARIBBBEAN ASSURANCE BROKERS LIMITED",
      volume: "7,236",
      c_price: "2.63",
      price_change: "0.01",
      change: "0.38",
    },
    {
      ticker: "CCC",
      name: "CARIBBEAN CEMENT COMPANY LTD.",
      volume: "52,936",
      c_price: "70.95",
      price_change: "0.73",
      change: "1.04",
    },
    {
      ticker: "KREMI",
      name: "CARIBBEAN CREAM LIMITED",
      volume: "18,870",
      c_price: "5.29",
      price_change: "0.01",
      change: "0.19",
    },
    {
      ticker: "CFF",
      name: "CARIBBEAN FLAVOURS & FRAGRANCES LIMITED",
      volume: "57,155",
      c_price: "2.00",
      price_change: "0.04",
      change: "2.04",
    },
    {
      ticker: "CPJ",
      name: "CARIBBEAN PRODUCERS JAMAICA LIMITED",
      volume: "79,560",
      c_price: "18.03",
      price_change: "0.02",
      change: "0.11",
    },
    {
      ticker: "CAR",
      name: "CARRERAS LIMITED",
      volume: "52,826",
      c_price: "9.72",
      price_change: "0.14",
      change: "1.46",
    },
    {
      ticker: "PURITY",
      name: "CONSOLIDATED BAKERIES (JAMAICA) LIMITED",
      volume: "490,067",
      c_price: "1.38",
      price_change: "0.04",
      change: "2.99",
    },
    {
      ticker: "ELITE",
      name: "ELITE DIAGNOSTIC LIMITED",
      volume: "25,328",
      c_price: "3.68",
      price_change: "0.09",
      change: "2.51",
    },
    {
      ticker: "EPLY7.50",
      name: "EPPLEY 7.50% PREF SHARES DUE 2024",
      volume: "132",
      c_price: "7.80",
      price_change: "0.65",
      change: "9.09",
    },
    {
      ticker: "EPLY",
      name: "EPPLEY LIMITED",
      volume: "1,061",
      c_price: "40.52",
      price_change: "0.42",
      change: "1.05",
    },
    {
      ticker: "EPLY6.00",
      name: "EPPLEY LTD 6% PREF SHARES DUE 2024",
      volume: "2,000",
      c_price: "1.10",
      price_change: "0.14",
      change: "15.00",
    },
    {
      ticker: "EFRESH",
      name: "EVERYTHING FRESH LIMITED",
      volume: "439,408",
      c_price: "1.75",
      price_change: "0.24",
      change: "15.89",
    },
    {
      ticker: "FTNA",
      name: "FONTANA LIMITED",
      volume: "190,631",
      c_price: "11.02",
      price_change: "0.11",
      change: "1.01",
    },
    {
      ticker: "FOSRICH",
      name: "FOSRICH COMPANY LIMITED",
      volume: "133,446",
      c_price: "28.97",
      price_change: "0.59",
      change: "2.08",
    },
    {
      ticker: "GENAC",
      name: "GENERAL ACCIDENT INSURANCE COMPANY (JA) LIMITED",
      volume: "466",
      c_price: "6.11",
      price_change: "0.16",
      change: "2.69",
    },
    {
      ticker: "GK",
      name: "GRACEKENNEDY LIMITED",
      volume: "32,691",
      c_price: "108.22",
      price_change: "2.40",
      change: "2.27",
    },
    {
      ticker: "GHL",
      name: "GUARDIAN HOLDINGS LIMITED",
      volume: "2,583",
      c_price: "520.01",
      price_change: "4.96",
      change: "0.96",
    },
    {
      ticker: "HONBUN",
      name: "HONEY BUN (1982) LIMITED",
      volume: "4,661",
      c_price: "9.67",
      price_change: "0.47",
      change: "5.11",
    },
    {
      ticker: "ICREATE",
      name: "ICREATE LIMITED ORDINARY SHARES",
      volume: "1,077,376",
      c_price: "2.93",
      price_change: "0.52",
      change: "21.58",
    },
    {
      ticker: "INDIES",
      name: "INDIES PHARMA JAMAICA LIMITED ORDINARY SHARES",
      volume: "53,430",
      c_price: "3.29",
      price_change: "0.17",
      change: "5.45",
    },
    {
      ticker: "JBG",
      name: "JAMAICA BROILERS GROUP",
      volume: "9,708",
      c_price: "28.37",
      price_change: "0.25",
      change: "0.89",
    },
    {
      ticker: "JP",
      name: "JAMAICA PRODUCERS GROUP LTD.",
      volume: "1,024,408",
      c_price: "23.99",
      price_change: "1.76",
      change: "7.92",
    },
    {
      ticker: "JSE",
      name: "JAMAICA STOCK EXCHANGE",
      volume: "47,378",
      c_price: "22.70",
      price_change: "2.53",
      change: "12.54",
    },
    {
      ticker: "JFP",
      name: "JFP LIMITED",
      volume: "498,060",
      c_price: "1.21",
      price_change: "0.03",
      change: "2.54",
    },
    {
      ticker: "JMMBGL",
      name: "JMMB GROUP LIMITED",
      volume: "289,920",
      c_price: "46.28",
      price_change: "0.19",
      change: "0.41",
    },
    {
      ticker: "JMMBGLUSD6.00",
      name: "JMMB GROUP LIMITED 6.00% USD",
      volume: "15,235",
      c_price: "1.01",
      price_change: "0.01",
      change: "1.22",
    },
    {
      ticker: "JMMBGL7.35",
      name: "JMMB GROUP LIMITED 7.35% CUMULATIVE REDEEMABLE PREFERENCE SHARE",
      volume: "64,649",
      c_price: "3.18",
      price_change: "0.03",
      change: "0.95",
    },
    {
      ticker: "KEY",
      name: "KEY INSURANCE COMPANY LIMITED",
      volume: "1,870",
      c_price: "4.88",
      price_change: "0.08",
      change: "1.67",
    },
    {
      ticker: "KW",
      name: "KINGSTON WHARVES LIMITED",
      volume: "26,805",
      c_price: "40.75",
      price_change: "0.87",
      change: "2.18",
    },
    {
      ticker: "LASM",
      name: "LASCO MANUFACTURING LIMITED",
      volume: "40,838",
      c_price: "5.43",
      price_change: "0.32",
      change: "6.26",
    },
    {
      ticker: "MAILPAC",
      name: "MAILPAC GROUP LIMITED",
      volume: "135,394",
      c_price: "3.12",
      price_change: "0.03",
      change: "0.97",
    },
    {
      ticker: "MEEG",
      name: "MAIN EVENT ENTERTAINMENT GROUP",
      volume: "28,476",
      c_price: "9.99",
      price_change: "0.04",
      change: "0.40",
    },
    {
      ticker: "MTL",
      name: "MARGARITAVILLE (TURKS) LIMITED",
      volume: "11",
      c_price: "25.50",
      price_change: "0.50",
      change: "2.00",
    },
    {
      ticker: "MASSY",
      name: "MASSY HOLDINGS LTD",
      volume: "6,045",
      c_price: "98.72",
      price_change: "0.52",
      change: "0.53",
    },
    {
      ticker: "MIL",
      name: "MAYBERRY INVESTMENTS LIMITED",
      volume: "23,945",
      c_price: "8.45",
      price_change: "0.32",
      change: "3.94",
    },
    {
      ticker: "MDS",
      name: "MEDICAL DISPOSABLES & SUPPLIES LIMITED",
      volume: "135,187",
      c_price: "6.26",
      price_change: "0.20",
      change: "3.30",
    },
    {
      ticker: "PAL",
      name: "PALACE AMUSEMENT CO. LTD.",
      volume: "18",
      c_price: "950.01",
      price_change: "10.01",
      change: "1.06",
    },
    {
      ticker: "PJAM",
      name: "PANJAM INVESTMENT LIMITED",
      volume: "36,337",
      c_price: "65.83",
      price_change: "1.78",
      change: "2.78",
    },
    {
      ticker: "PBS",
      name: "PRODUCTIVE BUSINESS SOLUTION LTD USD ORDINARY SHARES",
      volume: "410",
      c_price: "1.19",
      price_change: "0.16",
      change: "15.53",
    },
    {
      ticker: "PROVEN",
      name: "PROVEN INVESTMENTS LIMITED USD",
      volume: "12,818",
      c_price: "0.26",
      price_change: "0.01",
      change: "4.25",
    },
    {
      ticker: "SJ",
      name: "SAGICOR GROUP JAMAICA LIMITED",
      volume: "18,685",
      c_price: "56.52",
      price_change: "0.44",
      change: "0.78",
    },
    {
      ticker: "SPURTREE",
      name: "SPUR TREE SPICES JAMAICA LIMITED",
      volume: "679,715",
      c_price: "4.31",
      price_change: "0.08",
      change: "1.89",
    },
    {
      ticker: "SOS",
      name: "STATIONERY AND OFFICE SUPPLIES LIMITED",
      volume: "29,964",
      c_price: "9.28",
      price_change: "0.28",
      change: "3.11",
    },
    {
      ticker: "SIL",
      name: "STERLING INVESTMENTS LIMITED",
      volume: "26,005",
      c_price: "3.00",
      price_change: "0.01",
      change: "0.33",
    },
    {
      ticker: "SIL",
      name: "STERLING INVESTMENTS LIMITED USD",
      volume: "143",
      c_price: "0.02",
      price_change: "0.00",
      change: "1.85",
    },
    {
      ticker: "SVL",
      name: "SUPREME VENTURES LIMITED",
      volume: "583,185",
      c_price: "28.63",
      price_change: "0.44",
      change: "1.56",
    },
    {
      ticker: "SCIJMD",
      name: "SYGNUS CREDIT INVESTMENTS LIMITED JMD ORDINARY SHARES",
      volume: "44,031",
      c_price: "15.95",
      price_change: "0.39",
      change: "2.51",
    },
    {
      ticker: "SRFUSD",
      name: "SYGNUS REAL ESTATE FINANCE LIMITED (USD)",
      volume: "130",
      c_price: "0.14",
      price_change: "0.02",
      change: "14.33",
    },
    {
      ticker: "SRFJMD",
      name: "SYGNUS REAL ESTATE FINANCIAL LIMITED (JMD)",
      volume: "3,081",
      c_price: "16.29",
      price_change: "0.29",
      change: "1.81",
    },
    {
      ticker: "LAB",
      name: "THE LIMNERS AND BARDS LIMITED",
      volume: "2,768",
      c_price: "3.25",
      price_change: "0.01",
      change: "0.31",
    },
    {
      ticker: "TTECH",
      name: "TTECH LIMITED",
      volume: "10,000",
      c_price: "4.06",
      price_change: "0.16",
      change: "4.10",
    },
    {
      ticker: "VMIL",
      name: "VICTORIA MUTUAL INVESTMENTS LTD ORDINARY SHARES",
      volume: "112,985",
      c_price: "6.08",
      price_change: "0.01",
      change: "0.16",
    },
    {
      ticker: "WISYNCO",
      name: "WISYNCO GROUP LTD ORDINARY SHARES",
      volume: "242,465",
      c_price: "24.23",
      price_change: "0.61",
      change: "2.58",
    },
  ],
  declining: [
    {
      ticker: "1834",
      name: "1834 INVESTMENTS LIMITED",
      volume: "1,548,190",
      c_price: "1.26",
      price_change: "-0.03",
      change: "-2.33",
    },
    {
      ticker: "BRG",
      name: "BERGER PAINTS JAMAICA LTD.",
      volume: "101",
      c_price: "11.82",
      price_change: "-0.17",
      change: "-1.42",
    },
    {
      ticker: "CBNY",
      name: "CIBONEY GROUP LIMITED",
      volume: "279,430",
      c_price: "0.69",
      price_change: "-0.01",
      change: "-1.43",
    },
    {
      ticker: "DTL",
      name: "DERRIMON TRADING COMPANY LIMITED",
      volume: "1,996,001",
      c_price: "2.78",
      price_change: "-0.04",
      change: "-1.42",
    },
    {
      ticker: "DCOVE",
      name: "DOLPHIN COVE LIMITED",
      volume: "57,281",
      c_price: "21.22",
      price_change: "-1.03",
      change: "-4.63",
    },
    {
      ticker: "LEARN",
      name: "EDUFOCAL LIMITED",
      volume: "668,026",
      c_price: "3.10",
      price_change: "-0.03",
      change: "-0.96",
    },
    {
      ticker: "CPFV",
      name: "EPPLEY CARIBBEAN PROPERTY FUND LIMITED SCC",
      volume: "10,977",
      c_price: "42.00",
      price_change: "-5.00",
      change: "-10.64",
    },
    {
      ticker: "ECL",
      name: "EXPRESS CATERING LIMITED",
      volume: "34,223,943",
      c_price: "5.29",
      price_change: "-0.93",
      change: "-14.95",
    },
    {
      ticker: "FESCO",
      name: "FUTURE ENERGY SOURCE COMPANY LTD ORDINARY SHARES",
      volume: "1,753,220",
      c_price: "6.07",
      price_change: "-0.02",
      change: "-0.33",
    },
    {
      ticker: "ROC",
      name: "IRONROCK INSURANCE COMPANY LIMITED",
      volume: "40,280",
      c_price: "3.29",
      price_change: "-0.27",
      change: "-7.58",
    },
    {
      ticker: "JPS9.5",
      name: "JAMAICA PUBLIC SERVICE CO. 9.5%",
      volume: "2,550",
      c_price: "2,650.00",
      price_change: "-378.57",
      change: "-12.50",
    },
    {
      ticker: "JAMT",
      name: "JAMAICAN TEAS LIMITED",
      volume: "328,301",
      c_price: "3.56",
      price_change: "-0.02",
      change: "-0.56",
    },
    {
      ticker: "JETCON",
      name: "JETCON CORPORATION LIMITED",
      volume: "186,314",
      c_price: "1.85",
      price_change: "-0.07",
      change: "-3.65",
    },
    {
      ticker: "JMMBGL7.15",
      name: "JMMB GROUP LIMITED 7.15% CUMULATIVE REDEEMABLE PREFERENCE SHARE",
      volume: "86,000",
      c_price: "3.00",
      price_change: "-0.01",
      change: "-0.33",
    },
    {
      ticker: "KLE",
      name: "K.L.E. GROUP LIMITED",
      volume: "1",
      c_price: "2.60",
      price_change: "-0.06",
      change: "-2.26",
    },
    {
      ticker: "KPREIT",
      name: "KINGSTON PROPERTIES LIMITED",
      volume: "92,218",
      c_price: "7.60",
      price_change: "-0.75",
      change: "-8.98",
    },
    {
      ticker: "KEX",
      name: "KNUTSFORD EXPRESS SERVICES LIMITED",
      volume: "26,366",
      c_price: "7.99",
      price_change: "-0.01",
      change: "-0.13",
    },
    {
      ticker: "LASD",
      name: "LASCO DISTRIBUTORS LIMITED",
      volume: "130",
      c_price: "3.46",
      price_change: "-0.01",
      change: "-0.29",
    },
    {
      ticker: "LASF",
      name: "LASCO FINANCIAL SERVICES LIMITED",
      volume: "253,006",
      c_price: "3.28",
      price_change: "-0.06",
      change: "-1.80",
    },
    {
      ticker: "LUMBER",
      name: "LUMBER DEPOT LIMITED",
      volume: "495,355",
      c_price: "3.50",
      price_change: "-0.06",
      change: "-1.69",
    },
    {
      ticker: "MJE",
      name: "MAYBERRY JAMAICAN EQUITIES LIMITED",
      volume: "208,821",
      c_price: "11.54",
      price_change: "-0.05",
      change: "-0.43",
    },
    {
      ticker: "NCBFG",
      name: "NCB FINANCIAL GROUP LIMITED",
      volume: "19,024",
      c_price: "111.73",
      price_change: "-0.78",
      change: "-0.69",
    },
    {
      ticker: "PTL",
      name: "PARAMOUNT TRADING (JAMAICA) LIMITED",
      volume: "552,705",
      c_price: "1.77",
      price_change: "-0.24",
      change: "-11.94",
    },
    {
      ticker: "PROVEN",
      name: "PROVEN INVESTMENTS LIMITED JMD",
      volume: "4,417",
      c_price: "36.00",
      price_change: "-0.08",
      change: "-0.22",
    },
    {
      ticker: "PULS",
      name: "PULSE INVESTMENTS LIMITED",
      volume: "536,860",
      c_price: "4.18",
      price_change: "-0.04",
      change: "-0.95",
    },
    {
      ticker: "QWI",
      name: "QWI INVESTMENTS LIMITED",
      volume: "456,239",
      c_price: "0.92",
      price_change: "-0.01",
      change: "-1.08",
    },
    {
      ticker: "RJR",
      name: "RADIO JAMAICA LIMITED",
      volume: "557,679",
      c_price: "2.86",
      price_change: "-0.08",
      change: "-2.72",
    },
    {
      ticker: "SELECTF",
      name: "SAGICOR SELECT FUNDS LIMITED - FINANCIAL",
      volume: "1,038,753",
      c_price: "0.51",
      price_change: "-0.01",
      change: "-1.92",
    },
    {
      ticker: "SELECTMD",
      name: "SAGICOR SELECT FUNDS LIMITED MANUFACTURING & DISTRIBUTION",
      volume: "114,099",
      c_price: "0.70",
      price_change: "-0.01",
      change: "-1.41",
    },
    {
      ticker: "SALF",
      name: "SALADA FOODS JAMAICA LTD.",
      volume: "10,766",
      c_price: "6.14",
      price_change: "-0.08",
      change: "-1.29",
    },
    {
      ticker: "SGJ",
      name: "SCOTIA GROUP JAMAICA LIMITED",
      volume: "28,370",
      c_price: "35.98",
      price_change: "-0.01",
      change: "-0.03",
    },
    {
      ticker: "SEP",
      name: "SEPROD LIMITED",
      volume: "35,139",
      c_price: "58.41",
      price_change: "-2.04",
      change: "-3.37",
    },
    {
      ticker: "SSLVC",
      name: "SSL VENTURE CAPITAL JAMAICA LIMITED",
      volume: "109,215",
      c_price: "1.60",
      price_change: "-0.13",
      change: "-7.51",
    },
    {
      ticker: "SML",
      name: "STANLEY MOTTA LIMITED ORDINARY SHARES",
      volume: "2,868",
      c_price: "5.46",
      price_change: "-0.04",
      change: "-0.73",
    },
    {
      ticker: "SCIUSD",
      name: "SYGNUS CREDIT INVESTMENTS LIMITED USD ORDINARY SHARES",
      volume: "12,045",
      c_price: "0.13",
      price_change: "0.00",
      change: "-0.62",
    },
    {
      ticker: "TJH",
      name: "TRANSJAMAICAN HIGHWAY LIMITED",
      volume: "1,365,374",
      c_price: "1.64",
      price_change: "-0.01",
      change: "-0.61",
    },
    {
      ticker: "TJH",
      name: "TRANSJAMAICAN HIGHWAY LIMITED (USD)",
      volume: "1,042,640",
      c_price: "0.01",
      price_change: "0.00",
      change: "-3.77",
    },
    {
      ticker: "TROPICAL",
      name: "TROPICAL BATTERY COMPANY LIMITED",
      volume: "1,506,791",
      c_price: "2.87",
      price_change: "-0.08",
      change: "-2.71",
    },
  ],
  trading_firm: [
    {
      ticker: "BIL",
      name: "BARITA INVESTMENTS LIMITED",
      volume: "7,988",
      c_price: "89.98",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "CAC9.50",
      name: "CAC 2000 9.5% CUMULATIVE REDEEMABLE PREF SHARES",
      volume: "535",
      c_price: "1.10",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "CWJDEFERREDA",
      name: "COMMUNITY & WORKERS OF JAMAICA CCU DEFFERED SHARE",
      volume: "454",
      c_price: "1.97",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "FIRSTROCKJMD",
      name: "FIRST ROCK CAPITAL HOLDINGS LIMITED",
      volume: "8,129",
      c_price: "12.00",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "FIRSTROCKUSD",
      name: "FIRST ROCK CAPITAL HOLDINGS LIMITED  (USD)",
      volume: "75",
      c_price: "0.08",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "GWEST",
      name: "GWEST CORPORATION LIMITED ORDINARY SHARES",
      volume: "5,506",
      c_price: "1.00",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "ISP",
      name: "ISP FINANCE SERVICES LIMITED",
      volume: "25",
      c_price: "29.50",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "JMMBGL7.00NC",
      name: "JMMB GROUP 7.00% VR JMD CR PREFERENCE SHARES",
      volume: "1,221",
      c_price: "1.99",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "JMMBGL7.25C",
      name: "JMMB GROUP 7.25% VR JMD CR PREFERENCE SHARES",
      volume: "533",
      c_price: "1.90",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "JMMBGL7.25",
      name: "JMMB GROUP LIMITED 7.25%",
      volume: "339",
      c_price: "2.90",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "JMMBGL7.50",
      name: "JMMB GROUP LIMITED 7.50%",
      volume: "1,675",
      c_price: "1.00",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "MTL",
      name: "MARGARITAVILLE (TURKS) LIMITED USD",
      volume: "24",
      c_price: "0.16",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "PBS9.75",
      name: "PRODUCTIVE BUSINESS SOLUTIONS LTD 9.75% CUMULATIVE REDEEMABLE",
      volume: "3",
      c_price: "120.00",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "XFUND",
      name: "SAGICOR REAL ESTATE X FUND LTD.",
      volume: "24,778",
      c_price: "8.30",
      price_change: "0",
      change: "0",
    },
    {
      ticker: "WIG",
      name: "WIGTON WINDFARM LIMITED ORDINARY SHARES",
      volume: "1,016,814",
      c_price: "0.66",
      price_change: "0",
      change: "0",
    },
  ],
  id: "6281101ea01a24d2a259b9d8",
  date: "2022-04-28",
};
